### ISSUE TITLE
无法找到task1的测试文件dataset_testA_for_task_1.json

### ISSUE THREAD

**Issue by eellll** [WENGSYX/CMIVQA_Baseline#13]
您好，想训练这个模型，但是无法找到task1的测试文件dataset_testA_for_task_1.json

**Comment by WENGSYX** [comment]
Hi, 现阶段您无需使用dataset_testA_for_task_1.json！

如果您想要测试，可以使用我们发布的Dev Set文件MMIVQA_DEV.json进行测试！

我们将在测试阶段提供相同格式的的Test Set文件，到时候您可以使用相对应的代码以生成Test Set的预测结果并提交给我们。

**Comment by qxxfd** [comment]
MMIVQA_DEV.json 文件在哪里下载呢
