### ISSUE TITLE
无法找到task23的测试集

### ISSUE THREAD

**Issue by eellll** [WENGSYX/CMIVQA_Baseline#14]
无法找到task23的测试集。

**Comment by WENGSYX** [comment]
你好！当前阶段，请使用我们所分发的Dev Set，对于task2，3任务，同样适用task1的dev数据集。

task2，3的Test阶段将不提供视频相关的id信息。Dev阶段为便于管理和分发数据集，我们将所有target信息都提供于同一个json文件中。但本仓库的task23预测代码将不会使用视频id信息，以保证跟Test阶段的一致性。
