### ISSUE TITLE
请问数据集里做特征提取的原视频在哪里？

### ISSUE THREAD

**Issue by eellll** [WENGSYX/CMIVQA_Baseline#15]
请问数据集里做特征提取的原视频在哪里？

**Comment by WENGSYX** [comment]
Hi，所有的原视频来自于youtube.com,考虑到版权和开源协议问题我们无法提供爬取的视频，但我们已经提供了经由I3D特征模型提取的各视频特征。如果你有需要，可以依据我们所提供的视频id，直接从youtube上查看相应的视频。例如，video_id号为I_d3jPzS0Nk，则意味着对应于https://www.youtube.com/watch?v=I_d3jPzS0Nk
