### ISSUE TITLE
bug:ValueError: Docstring can't be built for model MutualSL

### ISSUE THREAD

**Issue by Pobby321** [WENGSYX/CMIVQA_Baseline#3]
python main.py

raise ValueError(f"Docstring can't be built for model {model_class}")

**Comment by Pobby321** [comment]
work

**Comment by Xue-Yw** [comment]
我也遇到了这个问题，请问您是怎么解决的？

**Comment by WENGSYX** [comment]
> 我也遇到了这个问题，请问您是怎么解决的？

你好，请问您是哪个任务？如果是最新版的代码应当是解决了此问题。如果您的代码仍然不工作，您也可以尝试在huggingface的代码库中，注释掉”Docstring can't be built for model“相关的这行。之所以会导致这个的原因，是模型的名称末尾不是”Model“。

**Comment by Xue-Yw** [comment]
> > 我也遇到了这个问题，请问您是怎么解决的？
> 
> 你好，请问您是哪个任务？如果是最新版的代码应当是解决了此问题。如果您的代码仍然不工作，您也可以尝试在huggingface的代码库中，注释掉”Docstring can't be built for model“相关的这行。之所以会导致这个的原因，是模型的名称末尾不是”Model“。

我运行的是任务一的baseline，是昨天下载的MusualSL模型代码，应该是最新的

**Comment by WENGSYX** [comment]
> 

我猜测可能是huggingface/transformers的版本有点不对应，不过问题不大。进到transformers代码中手动注释报错的这行就能解决。

**Comment by Xue-Yw** [comment]
> 

请问您用的huggingface，transformers是什么版本呢，我注释报错以后还会有新的错误
![image](https://github.com/WENGSYX/CMIVQA_Baseline/assets/56827857/ee607b91-6e5b-4664-b017-98bb2ca238ff)

**Comment by WENGSYX** [comment]
> nsformers是什么版本呢，我注释报错以后还会有新的错

如果您是使用https://github.com/WENGSYX/MutualSL的代码，那么确实存在此问题。我已经修复了WENGSYX/MutualSL的代码。另外，此Baseline/task1的代码中不会出现此问题，您也可尝试此代码库中的代码。

**Comment by Xue-Yw** [comment]
> > nsformers是什么版本呢，我注释报错以后还会有新的错
> 
> 如果您是使用[https://github.com/WENGSYX/MutualSL的代码，那么确实存在此问题。我已经修复了WENGSYX/MutualSL的代码。另外，此Baseline/task1的代码中不会出现此问题，您也可尝试此代码库中的代码。](https://github.com/WENGSYX/MutualSL%E7%9A%84%E4%BB%A3%E7%A0%81%EF%BC%8C%E9%82%A3%E4%B9%88%E7%A1%AE%E5%AE%9E%E5%AD%98%E5%9C%A8%E6%AD%A4%E9%97%AE%E9%A2%98%E3%80%82%E6%88%91%E5%B7%B2%E7%BB%8F%E4%BF%AE%E5%A4%8D%E4%BA%86WENGSYX/MutualSL%E7%9A%84%E4%BB%A3%E7%A0%81%E3%80%82%E5%8F%A6%E5%A4%96%EF%BC%8C%E6%AD%A4Baseline/task1%E7%9A%84%E4%BB%A3%E7%A0%81%E4%B8%AD%E4%B8%8D%E4%BC%9A%E5%87%BA%E7%8E%B0%E6%AD%A4%E9%97%AE%E9%A2%98%EF%BC%8C%E6%82%A8%E4%B9%9F%E5%8F%AF%E5%B0%9D%E8%AF%95%E6%AD%A4%E4%BB%A3%E7%A0%81%E5%BA%93%E4%B8%AD%E7%9A%84%E4%BB%A3%E7%A0%81%E3%80%82)

好的谢谢，已解决
