### ISSUE TITLE
Broken Videos Fixed

### ISSUE THREAD

**Issue by cmivqa** [WENGSYX/CMIVQA_Baseline#4]
Dear Participants,

The video (ID: LILVsv4Ft_E, D_igZblZVp0) in the CMIVQA task dataset is corrupted.

Now, it is fixed and listed in the link [https://pan.baidu.com/s/1hbLF0n7m25FsaXeQJBIdHw?pwd=9874](https://pan.baidu.com/s/1hbLF0n7m25FsaXeQJBIdHw?pwd=9874). We have also updated the dataset for fixing this issue. 

It should be informed for those who have already downloaded the old datasets.

Thank you for your attention!

**Comment by WENGSYX** [comment]
We have fixed this issue in the dataset that we re-uploaded.
