### ISSUE TITLE
subtitle.json如何获得？

### ISSUE THREAD

**Issue by ZHOUSY-HH** [WENGSYX/CMIVQA_Baseline#5]

**Comment by ZHOUSY-HH** [comment]
网盘里面没有描述，也没有下载，这样连baseline都跑不起来。

**Comment by cmivqa** [comment]
您好，

网盘发布的是本次比赛的全部数据

祝好

**Comment by cmivqa** [comment]
您好，subtitle.json已经上传至网盘

祝好

**Comment by ZHOUSY-HH** [comment]
明白了

**Comment by ZHOUSY-HH** [comment]
有个新的问题，给的subtittle.json，有的以sr结尾，有的不以sr结尾，读取数据时只读取不以sr结尾的，有什么含义吗？
