### ISSUE TITLE
baseline 报错

### ISSUE THREAD

**Issue by c1393428962** [WENGSYX/CMIVQA_Baseline#6]
File "main.py", line 228, in collate_fn
    input_ids = torch.tensor(input_ids)
ValueError: expected sequence of length 1847 at dim 1 (got 2724)

batch改成64后
一个batch中的input_ids的各个input_id的length不一致无法使用tensor函数转为tensor

**Comment by WENGSYX** [comment]
你好，由于显存限制，我们建议（并且仅支持）使用batchsize = 1
