### ISSUE TITLE
Too many not_load_example.

### ISSUE THREAD

**Issue by 277CPS** [WENGSYX/CMIVQA_Baseline#9]
In general, how many examples are expected to be not loaded? The number of examples not loaded in my case seems to be excessive.

**Comment by WENGSYX** [comment]
Hello, there are two possible cases that may lead to not loading. The first case is that the relevant video lacks subtitle files. Considering that this baseline method relies on subtitle information, it will be unable to process videos that completely lack subtitle files, so they will be discarded. The second case is that the subtitle information is too long. Considering that the current GPU memory can hardly process excessively long text, max_len=2500 is preset in the CFG. When a video exceeds the subtitle length limit, it will be discarded.

If you want to reduce the number of unloaded videos, you can do so by increasing max_len (recommended 4000 or above), but on the premise that the GPU memory will not exceed the limit.

**Comment by 277CPS** [comment]
在运行test.py时
 0%|                                                                                                                                                        | 0/2937 [00:00<?, ?it/s[2]+  Killed                  python test.py
Killed
shape已经对齐了，检查了很多环节，不清楚是什么问题，您能帮我解答一下吗

**Comment by 277CPS** [comment]
就是main我是跑通了的，按道理说不应该是设备问题，test中检查了很多断点，数据也应该是读进去了，所使用的设备是4090。出现了以上的问题，test没有给出参数，想请问一下test的参数，以及您使用的设备条件。
